package modelo;
// Generated 11/06/2021 09:40:19 AM by Hibernate Tools 4.3.1



/**
 * Jugadores generated by hbm2java
 */
public class Jugadores  implements java.io.Serializable {


     private int cedula;
     private Equipo equipo;
     private String nombre;
     private int numAmarillas;
     private int numRojas;
     private int numGoles;

    public Jugadores() {
    }

    public Jugadores(int cedula, String nombre , Equipo equipo, int numAmarillas, int numRojas, int numGoles) {
       this.cedula = cedula;
       this.equipo = equipo;
       this.nombre = nombre;
       this.numAmarillas = numAmarillas;
       this.numRojas = numRojas;
       this.numGoles = numGoles;
    }
   
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public Equipo getEquipo() {
        return this.equipo;
    }
    
    public void setEquipo(Equipo equipo) {
        this.equipo = equipo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getNumAmarillas() {
        return this.numAmarillas;
    }
    
    public void setNumAmarillas(int numAmarillas) {
        this.numAmarillas = numAmarillas;
    }
    public int getNumRojas() {
        return this.numRojas;
    }
    
    public void setNumRojas(int numRojas) {
        this.numRojas = numRojas;
    }
    public int getNumGoles() {
        return this.numGoles;
    }
    
    public void setNumGoles(int numGoles) {
        this.numGoles = numGoles;
    }




}


